### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaComputing/NonlinearSolve.jl#17]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by avik-pal** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() branch=v1_backport

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by avik-pal** [comment]
@JuliaRegistrator register

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SCCNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveFirstOrder

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveSpectralMethods

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveQuasiNewton

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveFirstOrder

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveFirstOrder

@JuliaRegistrator register() subdir=lib/NonlinearSolveQuasiNewton

@JuliaRegistrator register() subdir=lib/NonlinearSolveSpectralMethods

@JuliaRegistrator register() subdir=lib/SimpleNonlinearSolve

@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveQuasiNewton

@JuliaRegistrator register() subdir=lib/NonlinearSolveSpectralMethods

@JuliaRegistrator register() subdir=lib/SimpleNonlinearSolve

@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveSpectralMethods

@JuliaRegistrator register() subdir=lib/SimpleNonlinearSolve

@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SimpleNonlinearSolve

@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveHomotopyContinuation

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveQuasiNewton

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveFirstOrder

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveHomotopyContinuation

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ytdHuang** [comment]
@ChrisRackauckas 
sorry that I forgot to update the version number to `1.4.1`

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SimpleNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SimpleNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BracketingNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BracketingNonlinearSolve

**Comment by oscardssmith** [comment]
@JuliaRegistrator register() subdir=lib/BracketingNonlinearSolve
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase
@JuliaRegistrator register() subdir=lib/NonlinearSolveFirstOrder
@JuliaRegistrator register() subdir=lib/NonlinearSolveQuasiNewton
@JuliaRegistrator register() subdir=lib/NonlinearSolveSpectralMethods
@JuliaRegistrator register() subdir=lib/SimpleNonlinearSolve
@JuliaRegistrator register() subdir=lib/SciMLJacobianOperators
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
Each needs to be a separate post, it'll only do the first one

**Comment by oscardssmith** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by oscardssmith** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveFirstOrder

**Comment by oscardssmith** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveQuasiNewton

**Comment by oscardssmith** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveSpectralMethods

**Comment by oscardssmith** [comment]
@JuliaRegistrator register() subdir=lib/SimpleNonlinearSolve

**Comment by oscardssmith** [comment]
@JuliaRegistrator register() subdir=lib/SciMLJacobianOperators

**Comment by oscardssmith** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveFirstOrder

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BracketingNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveFirstOrder

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveHomotopyContinuation

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveQuasiNewton

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveSpectralMethods

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SCCNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SciMLJacobianOperators

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SimpleNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveFirstOrder

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveQuasiNewton

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SciMLJacobianOperators

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveQuasiNewton

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SCCNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveHomotopyContinuation

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SciMLJacobianOperators

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SimpleNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveQuasiNewton

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() branch=v3-backport

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveQuasiNewton

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BracketingNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveSciPy

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SCCNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SCCNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SCCNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SciMLJacobianOperators

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveFirstOrder

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveQuasiNewton

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveQuasiNewton

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SciMLJacobianOperators

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveFirstOrder

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveQuasiNewton

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveSpectralMethods

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SciMLJacobianOperators

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveSciPy

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveSpectralMethods

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SCCNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SimpleNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by oscardssmith** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BracketingNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveFirstOrder

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BracketingNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveSpectralMethods



SimpleNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SimpleNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveFirstOrder

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveQuasiNewton

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveSpectralMethods

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SciMLJacobianOperators

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SciMLJacobianOperators

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveFirstOrder

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveQuasiNewton

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SimpleNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SCCNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/NonlinearSolveFirstOrder

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/BracketingNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/SimpleNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/NonlinearSolveFirstOrder

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/NonlinearSolveQuasiNewton

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/NonlinearSolveSpectralMethods

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/SciMLJacobianOperators

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/BracketingNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/NonlinearSolveFirstOrder

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/NonlinearSolveQuasiNewton

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/NonlinearSolveSpectralMethods

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/NonlinearSolveSciPy

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/NonlinearSolveHomotopyContinuation

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/SimpleNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/SCCNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SCCNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/SimpleNonlinearSolve

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveBase

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/NonlinearSolveHomotopyContinuation
